name: SPFx CICD with O365 CLI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash 
      - name: Isdocker
        run: ../isdocker.sh
        shell: bash 