name: SPFx CICD with O365 CLI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Display the path
        run: echo $PATH
        shell: bash 
      - name: ls
        run: ls
        shell: bash 
      - name: runsh
        run: chmod +x ./isdocker.sh
        shell: bash 
      - name: isdocker
        run:  if [ -f /.dockerenv ]; then echo "I'm inside matrix ;("; else echo "I'm living in real world!";fi
        shell: bash 
      - name: Office 365 CLI Login
        uses: VelinGeorgiev/action-cli-login@master
        env:
          ADMIN_USERNAME:  ${{ secrets.adminUsername }}
          ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
      - name: Office 365 CLI script
        uses: VelinGeorgiev/action-cli-runscript@master
        env:
          O365_CLI_SCRIPT: o365 spo tenant settings list
      - name: .o365cli-tokens.json exists
        run:  if [ -f /.o365cli-tokens.json ]; then echo ".o365cli-tokens.json exists"; else echo ".o365cli-tokens.json does not exist";fi
        shell: bash 

          
