name: SPFx CICD with O365 CLI
on: [push]
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - name: Office 365 CLI Login
      uses: VelinGeorgiev/action-cli-login@master
      env:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}