name: SPFx CICD with O365 CLI
on: [push]
jobs:
  deploy:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Office 365 CLI Login
        uses: VelinGeorgiev/action-cli-login@master
        with:
          ADMIN_USERNAME:  ${{ secrets.adminUsername }}
          ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
      - name: Office 365 CLI script
        uses: VelinGeorgiev/action-cli-runscript@master
        with:
          O365_CLI_SCRIPT: o365 spo tenant appcatalogurl get
          IS_POWERSHELL: false